repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: "âœ¨ Lint"
        entry: bash -c "cd frontend && npm run lint"
        language: system
        types: [file]
        files: ^frontend/src/.*\.(ts|tsx)$

      - id: npm-type-check
        name: "ğŸ§ Typecheck"
        entry: bash -c "cd frontend && npm run type-check"
        language: system
        types: [file]
        files: ^frontend/src/.*\.(ts|tsx)$

      - id: npm-build
        name: "ğŸ—ï¸  Build"
        entry: bash -c "cd frontend && npm run build"
        language: system
        pass_filenames: false
        always_run: true
        files: ^(frontend/(src/.*|package\.json|vite\.config\.ts|tailwind\.config\.js|tsconfig\.json))$
