repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: "âœ¨ Lint"
        entry: bash -c "cd frontend && npm run lint"
        language: system
        always_run: true

      - id: npm-type-check
        name: "ğŸ§ Typecheck"
        entry: bash -c "cd frontend && npm run type-check"
        language: system
        always_run: true

      - id: npm-build
        name: "ğŸ—ï¸ Build"
        entry: bash -c "cd frontend && npm run build"
        language: system
        always_run: true
